package com.xt.model;

public enum ProductClassification {

    LX_APPLY_SERVICE("LX_APPLY_SERVICE", "留学申请服务"),

    LX_APPLICANT_COUNTRY("LX_APPLICANT_COUNTRY", "加申辅申国家"),
    LX_APPLICANT_ADMISSION("LX_APPLICANT_ADMISSION", "加申入学申请"),
    LX_PROFESSIONAL_DIRECTION("LX_PROFESSIONAL_DIRECTION", "加申专业方向"),

    SINGLE_DOCUMENT("SINGLE_DOCUMENT", "单办文书"),
    SHORT_SIGN("SHORT_SIGN", "短签"),
    OTHER("OTHER", "其他"),

    APPLY_FAMOUS_SCHOOL("APPLY_FAMOUS_SCHOOL", "名校申请"),
    EARLY_BIRD("EARLY_BIRD", "早起鸟"),
    US_VISA_EXEMPTION("US_VISA_EXEMPTION", "美签免责"),
    DOUBLE_INSURANCE("DOUBLE_INSURANCE", "双保险"),

    LX_THIRD_PART_SERVICE("LX_THIRD_PART_SERVICE", "留学第三方服务"),

    FL_ACADEMIC("FL_ACADEMIC", "学术考试"),
    FL_DOMESTIC_LANGUAGE("FL_DOMESTIC_LANGUAGE", "国内语言考试"),
    FL_INTERNATIONAL_SUBJECT("FL_INTERNATIONAL_SUBJECT", "国际学科"),
    FL_COMPREHENSIVE_ENGLISH("FL_COMPREHENSIVE_ENGLISH", "综合英语"),
    FL_OVERSEA_LANGUAGE("FL_OVERSEA_LANGUAGE", "国外语言考试"),
    FL_PREPARATION_NATIONAL_HIGH_SCHOOL_EXAM("FL_PREPARATION_NATIONAL_HIGH_SCHOOL_EXAM", "国高备考"),

    OY_INTERNATIONAL_SUBJECT("OY_INTERNATIONAL_SUBJECT", "国际学科"),
    OY_DOMESTIC_LANGUAGE("OY_DOMESTIC_LANGUAGE", "国内语言考试"),
    OY_OVERSEA_LANGUAGE("OY_OVERSEA_LANGUAGE", "国外语言考试"),

    FL_PROJECT("FL_PROJECT", "项目"),
    OY_PROJECT("OY_PROJECT", "项目"),

    BG_ACADEMIC_RESEARCH("BG_ACADEMIC_RESEARCH", "背景提升类-学术科研"),
    BG_OVERSEAS_INTERNSHIP_EMPLOYMENT("BG_OVERSEAS_INTERNSHIP_EMPLOYMENT", "背景提升类-海外实习"),
    BG_PRESTIGIOUS_SCHOOL_APPLICATION_ASSISTANCE("BG_PRESTIGIOUS_SCHOOL_APPLICATION_ASSISTANCE", "背景提升类-名校申请助力"),
    BG_INTERNATIONAL_COURSES("BG_INTERNATIONAL_COURSES", "背景提升类-国际课程"),
    BG_KNOWLEDGE_CONTEST("BG_KNOWLEDGE_CONTEST", "背景提升类-知识竞赛"),
    BG_SOCIAL_PRACTICE("BG_SOCIAL_PRACTICE", "背景提升类-社会实践"),
    BG_CAREER_DISCOVERY("BG_CAREER_DISCOVERY", "背景提升类-职业发现"),
    BG_OVERSEAS_ACADEMIC_COUNSELING("BG_OVERSEAS_ACADEMIC_COUNSELING", "海外学业辅导类"),
    BG_OVERSEAS_EMPLOYMENT("BG_OVERSEAS_EMPLOYMENT", "海外就业类"),
    BJTS_COOPERATE("BJTS_COOPERATE", "背提合作"),
    XZC_OFFLINE_INTERNSHIP("XZC_OFFLINE_INTERNSHIP", "实习无忧计划-线下实习"),
    XZC_ONLINE_INTERNSHIP("XZC_ONLINE_INTERNSHIP", "实习无忧计划-线上实训"),
    XZC_ESCORT_PLAN("XZC_ESCORT_PLAN", "实习无忧计划-护航计划"),
    XZC_CAREER_EMPLOYMENT_PLAN("XZC_CAREER_EMPLOYMENT_PLAN", "就业无忧计划"),
    XZC_1V1_COUNSELING("XZC_1V1_COUNSELING", "1V1辅导"),
    XZC_INTEGRATED_PRODUCT("XZC_INTEGRATED_PRODUCT", "一体化产品"),
    XZC_PTA("XZC_PTA", "PTA"),
    XM_COURSE_AND_PROJECT("XM_COURSE_AND_PROJECT", "小麦课程和项目"),
    PACKAGE("PACKAGE", "套餐产品"),
    ;

    private String code;
    private String name;

    ProductClassification(String code, String name)
    {
        this.code = code;
        this.name = name;
    }

    public String getCode()
    {
        return code;
    }



}
